// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/stream.proto

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DSPStream_ProcessAudio_FullMethodName = "/stream.DSPStream/ProcessAudio"
)

// DSPStreamClient is the client API for DSPStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DSPStreamClient interface {
	// Bidirectional streaming of audio chunks
	ProcessAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AudioChunk], error)
}

type dSPStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewDSPStreamClient(cc grpc.ClientConnInterface) DSPStreamClient {
	return &dSPStreamClient{cc}
}

func (c *dSPStreamClient) ProcessAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DSPStream_ServiceDesc.Streams[0], DSPStream_ProcessAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, AudioChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DSPStream_ProcessAudioClient = grpc.BidiStreamingClient[AudioChunk, AudioChunk]

// DSPStreamServer is the server API for DSPStream service.
// All implementations must embed UnimplementedDSPStreamServer
// for forward compatibility.
type DSPStreamServer interface {
	// Bidirectional streaming of audio chunks
	ProcessAudio(grpc.BidiStreamingServer[AudioChunk, AudioChunk]) error
	mustEmbedUnimplementedDSPStreamServer()
}

// UnimplementedDSPStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDSPStreamServer struct{}

func (UnimplementedDSPStreamServer) ProcessAudio(grpc.BidiStreamingServer[AudioChunk, AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method ProcessAudio not implemented")
}
func (UnimplementedDSPStreamServer) mustEmbedUnimplementedDSPStreamServer() {}
func (UnimplementedDSPStreamServer) testEmbeddedByValue()                   {}

// UnsafeDSPStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DSPStreamServer will
// result in compilation errors.
type UnsafeDSPStreamServer interface {
	mustEmbedUnimplementedDSPStreamServer()
}

func RegisterDSPStreamServer(s grpc.ServiceRegistrar, srv DSPStreamServer) {
	// If the following call panics, it indicates UnimplementedDSPStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DSPStream_ServiceDesc, srv)
}

func _DSPStream_ProcessAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DSPStreamServer).ProcessAudio(&grpc.GenericServerStream[AudioChunk, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DSPStream_ProcessAudioServer = grpc.BidiStreamingServer[AudioChunk, AudioChunk]

// DSPStream_ServiceDesc is the grpc.ServiceDesc for DSPStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DSPStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.DSPStream",
	HandlerType: (*DSPStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessAudio",
			Handler:       _DSPStream_ProcessAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/stream.proto",
}
